<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Promise</title>
  </head>
  <body>
    <script src="https://unpkg.com/axios@0.2.1/dist/axios.min.js"></script>
    <h1>Promises...</h1>
    <script>
      axios
        .get("https://jsonplaceholder.typicode.com/todos/1")
        .then((res) => {
          console.log(res.data);
          return axios.get("https://jsonplaceholder.typicode.com/todos/2");
        })
        .then((res) => console.log(res.data))

        .catch(function (error) {
          console.log(error);
        });

      // Working with Promise Object
      let PromiseObject = new Promise((res, rej) => {
        rej("Didn't work");
        res("Resolved!");
      });
      PromiseObject.then(
        (data) => console.log(data),
        (err) => console.log(err)
      )
        .catch((e) => console.log(e))
        .finally(() => console.log("finally"));

      // Doing network stuff with Promises
      let some_url = "https://jsonplaceholder.typicode.com/todos/100";

      const some_ajax = (url) => {
        return new Promise((resolve, reject) => {
          let xhr = new XMLHttpRequest();
          xhr.open("GET", url, true);
          xhr.onreadystatechange = function () {
            if (this.readyState == 4) {
              if (this.status == 200) {
                resolve(JSON.parse(this.responseText));
              } else {
                reject(`ERR: ${this.status}. That's not cool...`);
              }
              th;
            }
            //else { reject("This stuff does not fly"); }
          };
          xhr.send();
        });
      };

      const newPO = some_ajax(some_url);
      newPO.then((d) => console.log(d)).catch((e) => console.error(e));

      // Generating stupid array of promises to work with it
      const promiseArray = [];
      for (let i = 0; i <= 10; i++) {
        promiseArray.push(
          new Promise((resolve, reject) => {
            const time = Math.floor(Math.random() * 1000 * 3);
            setTimeout(() => {
              time % 2 === 1
                ? resolve(`Resolved with time: ${time}`)
                : reject(`Rejected with time: ${time}`);
            }, time);
          })
        );
      }

      promiseArray.forEach((item) =>
        item.then((val) => console.log(val)).catch((e) => console.error(e))
      );

      // First
      const first = Promise.race(promiseArray);
      first
        .then((d) => console.log(`first: ${d}`))
        .catch((e) => console.error(`first error: ${e}`));

      // All settled
      const allSettled = Promise.allSettled(promiseArray);
      allSettled.then((res) =>
        res.forEach((res) => {
          if (res.hasOwnProperty("value")) {
            console.log("value is ", res.value);
          } else if (res.hasOwnProperty("reason")) {
            console.error(
              "we dont care about the error " +
                res.reason +
                " but here it is, btw..."
            );
          }
        })
      );

      // All
      const all = Promise.all(promiseArray);
      all
        .then((res) => console.log(res))
        .catch((e) =>
          console.error(
            "Allways catching " +
              e +
              " ALLEWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYS!!!!"
          )
        );
    </script>
  </body>
</html>
